---
# tasks file for roles/named

- name: install dependencies
  become: true
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - bind-chroot
    # - nm-connection-editor
    # - NetworkManager-glib
    # - NetworkManager-libnm
    # - python3-libsemanage
    # - python3-policycoreutils

- name: add DNS service to firewall
  become: true
  firewalld:
    service: dns
    permanent: yes
    state: enabled
  notify:
    - restart firewalld
    - enable and start named
