---
# tasks file for roles/vault

- name: install rpm keys
  become: yes
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://rpm.releases.hashicorp.com/gpg

- name: Install HashiCorp repo
  become: yes
  get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install packages
  become: yes
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Copy Vault systemd service
  become: yes
  copy:
    src: vault.service
    dest: /etc/systemd/system/vault.service
    mode: '0644'

- name: Create Vault system group
  become: yes
  group:
    name: vault
    state: present
    system: yes

- name: Create Vault user
  become: yes
  user:
    name: vault
    home: /etc/vault.d
    system: yes
    shell: /bin/false
    group: vault

- name: just force systemd to re-execute itself (2.8 and above)
  become: yes
  systemd:
    daemon_reexec: yes

- name: Allow the service to be accessed at the firewall level
  become: yes
  firewalld:
    port: 8200/tcp
    permanent: yes
    state: enabled
  notify: Restart Firewalld

- name: Allow the service to be accessed at the firewall level
  become: yes
  firewalld:
    port: 8201/tcp
    permanent: yes
    state: enabled
  notify: Restart Firewalld

# - name: install packages
#   become: yes
#   package:
#     name: "{{ item }}"
#     update_cache: yes
#   with_items: "{{ vault_install_prerequisites }}"

# - name: download Hashicorp Vault
#   unarchive:
#     src: https://releases.hashicorp.com/vault/1.6.1/vault_1.6.1_linux_amd64.zip
#     dest: /tmp
#     remote_src: yes

# - name: copy Vault binary
#   become: yes
#   copy:
#     src: /tmp/vault
#     dest: /usr/local/bin
#     mode: a+x
#     remote_src: yes
