---
# configuration tasks file for roles/libvirt

- name: uncomment line from /etc/libvirt/libvirtd.conf
  become: true
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    insertafter: "{{ item.pattern }}"
    line: "{{ item.value }}"
    state: present
  loop:
    - {pattern: '^#?unix_sock_group = "libvirt"', value: 'unix_sock_group = "libvirt"'}
    - {pattern: '^#?unix_sock_rw_perms = "0770"', value: 'unix_sock_rw_perms = "0770"'}
  notify: restart libvirtd

# In order to grant quemu access to my users directories i modified /etc/libvirt/qemu.conf file.
# [Link to GitHub](https://github.com/jedi4ever/veewee/issues/996#issuecomment-536519623)
- name: set qemu user in /etc/libvirt/qemu.conf
  become: true
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    insertafter: "{{ item.pattern }}"
    line: "{{ item.value }}"
    state: present
  loop:
    - {pattern: '^#?user = (?!{{ become_user }})', value: 'user = "{{ become_user }}"'}
    - {pattern: '^#?group = (?!{{ become_user }})', value: 'group = "{{ become_user }}"'}
  notify: restart libvirtd

- name: define a new network
  virt_net:
    command: define
    name: virbr0
    xml: '{{ lookup("template", "network/bridge.xml.j2") }}'

- name: start a network
  virt_net:
    command: create
    name: virbr0

- name: autostart a network
  virt_net:
    autostart: yes
    name: virbr0

- name: create KVM userspace direcories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'
  loop:
    - "{{ libvirt_dir_iso }}"
    - "{{ libvirt_dir_images }}"
    - "{{ libvirt_dir_pools }}"

- name: Create libvirt userspace config directory
  file:
    path: $HOME/.config/libvirt
    state: directory
    mode: '0755'

- name: Copy default config file to allow virsh to use qemu:///system
  become: yes
  copy:
    src: /etc/libvirt/libvirt.conf
    dest: /home/{{ become_user }}/.config/libvirt/libvirt.conf
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    remote_src: yes

- name: Use qemu:///system for virsh by default
  replace:
    path: $HOME/.config/libvirt/libvirt.conf
    regexp: '#uri_default = "qemu:///system'
    replace: 'uri_default = "qemu:///system'
