---
# tasks file for install_matchbox

- name: Install dependencies
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - tar
  become: yes

- name: Download Matchbox
  unarchive:
    src: https://github.com/poseidon/matchbox/releases/download/v0.8.0/matchbox-v0.8.0-linux-amd64.tar.gz
    dest: $HOME
    remote_src: yes

- name: Copy Matchbox binary
  copy:
    src: $HOME/matchbox-v0.8.0-linux-amd64/matchbox
    dest: /usr/local/bin
    mode: a+x
    remote_src: yes

- name: Copy Matchbox example systemd unit to allow starting matchbox at boot
  copy:
    src: $HOME/matchbox-v0.8.0-linux-amd64/contrib/systemd/matchbox-local.service
    dest: /etc/systemd/system/matchbox.service
    remote_src: yes
    mode: 0644

- name: Create Matchbox system group
  group:
    name: matchbox
    state: present
    system: yes

- name: Create Matchbox user
  user: 
    name: matchbox
    system: yes
    group: matchbox

- name: just force systemd to re-execute itself (2.8 and above)
  systemd:
    daemon_reexec: yes

- name: Create Matchbox directories
  file:
    path: '{{ item }}'
    state: directory
    owner: matchbox
    group: matchbox
    mode: 0755
  loop:
    - /etc/matchbox
    - /var/lib/matchbox/assets
    - /var/lib/matchbox/groups
    - /var/lib/matchbox/ignition
    - /var/lib/matchbox/profiles

- name: Allow the service to be accessed at the firewall level
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
  notify: Restart Firewalld

- name: Start Matchbox service
  service: 
    name: matchbox
    state: started
    enabled: yes